# Generated by Django 2.0.5 on 2019-04-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DateTimeField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Getting_marks', models.IntegerField()),
                ('result_date', models.DateField()),
                ('days', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='new2app.ExamTime')),
            ],
        ),
        migrations.CreateModel(
            name='StudentName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='examtime',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='new2app.StudentName'),
        ),
    ]
