# Generated by Django 2.0.5 on 2019-04-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhour',
            name='days',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
