# Generated by Django 2.0.5 on 2019-04-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Signup',
        ),
    ]
